carts/urls.py
"""carts URL Configuration"""

from django.urls import path

from .views import (
    cart_home,
    cart_update,
    )

app_name = "carts"

urlpatterns = [
    path('', cart_home, name="home"),
    path('/update', cart_update, name="update")
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


from .views import (
    home_page,
    about_page,
    contact_page,
    login_page,
    register_page
    )

urlpatterns = [
    path('', home_page, name="home"),
    path('about', about_page, name="about"),
    path('contact', contact_page, name="contact"),
    path('login', login_page, name="login"),
    path('cart', include("carts.urls", namespace="cart")),
    path('register', register_page, name="register"),
    path('products', include("products.urls", namespace="products")),
    path('search', include("search.urls", namespace="search")),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

products/urls.py
"""products URL Configuration"""

from django.urls import path

from .views import (
    ProductListView,
    ProductDetailSlugView,
    )

app_name = "products"

urlpatterns = [
    path('', ProductListView.as_view(), name="list"),
    path('/<str:slug>', ProductDetailSlugView.as_view(), name="detail")
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

<!-- Font awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

templates/base/js.html
<!-- Optional JavaScript -->
{% load static %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

templates/base/nav.html
<!-- <h1>{{brand_name}}</h1> -->
{% url 'home' as home_url %}
{% url 'products:list' as product_list_url %}
{% url 'about' as about_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %}{{brand_name}}{% else %} Navbar{% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
            <a class="nav-link" href="{{home_url}}">Home</a>
            </li>
            <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                <a class="nav-link" href="{{product_list_url}}">Products</a>
            </li>
            <li class="nav-item {% if request.path == about_url %}active{% endif %}">
            <a class="nav-link" href="{{ about_url }}">About</a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                <a class="nav-link" href="{{ contact_url }}">contact</a>
            </li>
            <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                <a class="nav-link disabled" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link disabled" href="{{ logout_url }}">logout</a>
            </li>
            {% else %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link disabled" href="{{ login_url }}">login</a>
            </li>
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                <a class="nav-link disabled" href="{{ register_url }}">Register</a>
            </li>
            {% endif %}
        </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
  </nav>